### ISSUE TITLE
find typo

### ISSUE THREAD

**Issue by ymstshinichiro** [shoota/shoota#101]
[ultra super nits]
毎度めざとくてすみません 🙏 

https://github.com/shoota/shoota/blob/d4a253264c66026d07c1df1879344416c50a5412/components/organisms/Hero.tsx#L20
「欠けているも方」 -> 「欠けているものの方」 かなと。
(もしかしてですが、あえて文章を欠けさせているっていう高度な表現だったら野暮なツッコミで本当に申し訳ない)

PR立てようと思ったんですが権限なかったのでissueで報告させていただきました。

追伸:
こちらはみんな元気です！

**Comment by shoota** [comment]
@ymstshinichiro 全然気づいてなかったｗｗｗｗ

**Comment by ymstshinichiro** [comment]
@shoota  いえいえwww リニューアル楽しみにしてます！！！！
